#!/bin/bash

# Build Tranquility.
docker build -t tranquility-dev -f Dockerfile.dev .

# Start the webserver and Webpack.
docker run -p 3000:80 \
           -v `pwd`/dashboards:/user/dashboards \
           -v `pwd`/docker:/app/docker \
           -v `pwd`/client:/app/client \
           -v `pwd`/server:/app/server \
           -e "DEBUG=$DEBUG" \
           --rm -it \
           --name tranquility-dev \
           tranquility-dev
