#!/bin/bash

# Build Tranquility.
docker build -t tranquility-dev -f Dockerfile.dev .

# Start the webserver and Webpack.
docker run -p 3000:80 \
           -v "$(pwd):/app" \
           -e "DEBUG=$DEBUG" \
           --rm -it \
           tranquility-dev
